### ISSUE TITLE
Still being developed, or known alternative?

### ISSUE THREAD

**Issue by remorse** [mgreter/sass.link.js#3]
Hi! I have no intention of being pushy, but it looks like this project would solve an annoying development issue for me, and I was wondering if there are any plans to resurrect it? Or, if not, are there any other projects that you know of which do something similar?

Basically, I am working with some people who cannot install SASS on their development computers. Something like this project would let us develop everything as SCSS, and then before going live, I could compile the files into actual CSS.

Thanks,
Ricky

**Comment by mgreter** [comment]
No, this is not "actively" maintained, since I have a) too much on the plate and b) have decided to step back a bit on my OSS contributions. After all this was merely a hacky way to get something going. Problem beeing that I do not know how to intercept FS lookups with newer sass.js versions. But there are alternatives:

https://github.com/sass/node-sass
https://github.com/sass/perl-libsass
https://github.com/medialize/sass.js/

Best regards
Marcel

**Comment by mgreter** [comment]
Closed as duplicate of https://github.com/mgreter/sass.link.js/issues/2

**Comment by remorse** [comment]
Thanks for the update. The thing I liked about this was that it was entirely within the webpage, so that I didn't have to have a server or anything set up to do the development. I guess I'll look around some more.
